version: '3'

services:
  postgres:
    image: postgres:10
    container_name: postgres-lab
    restart: always
    ports:
      - "32773:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis-lab
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
