version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    networks:
      - back-tier
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - back-tier

networks:
  back-tier: {}


